"""empty message

Revision ID: 80a46bac817a
Revises: 
Create Date: 2025-04-19 00:59:28.295298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '80a46bac817a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_user', schema=None) as batch_op:
        batch_op.drop_index('ix_base_user_sub')

    op.drop_table('base_user')
    with op.batch_alter_table('role_update', schema=None) as batch_op:
        batch_op.drop_index('ix_role_update_id')

    op.drop_table('role_update')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_update',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('sub', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_service_provider', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sub'], ['base_user.sub'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_update', schema=None) as batch_op:
        batch_op.create_index('ix_role_update_id', ['id'], unique=False)

    op.create_table('base_user',
    sa.Column('sub', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('picture', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_service_provider', sa.BOOLEAN(), nullable=True),
    sa.Column('user_rating', sa.FLOAT(), nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address_line1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address_line2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('province_or_state', sa.VARCHAR(length=100), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('weekly_schedule', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('sub'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('base_user', schema=None) as batch_op:
        batch_op.create_index('ix_base_user_sub', ['sub'], unique=False)

    # ### end Alembic commands ###
